"""
RajMill - milling chatter stability and surface finish predictor (single file)

Generated by tools/build_single_file.py - do not edit this file directly.
Edit core/ and views/ in the main project, then re-run the build script.

Deploy: put this one file plus requirements.txt in a repo and point Streamlit
Community Cloud at app.py. Nothing else is needed.
"""
from __future__ import annotations

import json
import warnings
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.io as pio
import streamlit as st

ROOT = Path(__file__).resolve().parent


# -------------------------------------------------------------------------
# core/theme.py
# -------------------------------------------------------------------------
# Shared look and feel: page config, CSS and the Plotly template.
#
# Everything visual lives here so the pages stay about signals, not styling.


APP_NAME = "RajMill"          # rename the app here
CONTACT = "you@example.com"

INK = "#15233a"
INK_2 = "#5a6b7e"
GRID = "#e2e8ec"
SIGNAL = "#2451d6"
DETAIL = "#d98e04"
GOOD = "#1f7a4d"
BAD = "#b3261e"
BAND_COLORS = ["#2451d6", "#d98e04", "#b3651c", "#6b7a3a", "#3f8f8a", "#7a4fa3",
               "#a33a5b", "#8a5a00"]

_template = go.layout.Template()
_template.layout = go.Layout(
    font=dict(family="Archivo, Helvetica Neue, Arial, sans-serif", color=INK, size=13),
    paper_bgcolor="white",
    plot_bgcolor="white",
    margin=dict(l=60, r=20, t=30, b=45),
    xaxis=dict(gridcolor=GRID, zerolinecolor="#cbd5dd", linecolor="#cbd5dd"),
    yaxis=dict(gridcolor=GRID, zerolinecolor="#cbd5dd", linecolor="#cbd5dd"),
    legend=dict(orientation="h", y=1.12, x=0),
    colorway=BAND_COLORS,
)
pio.templates["signalbench"] = _template
pio.templates.default = "signalbench"

CSS = """
<style>
  /* Cambria everywhere, matching the Raj3DLabs house style (falls back to Georgia
     / Times on Mac, Android and Linux). Icons and code keep their own fonts. */
  .stApp *:not([data-testid="stIconMaterial"]):not(code):not(pre):not(pre *) {
      font-family: Cambria, "Cambria Math", Georgia, "Times New Roman", serif !important;}
  .block-container {padding-top: 3.2rem; max-width: 1180px;}
  .rm-brand {font-size: 2.4rem; font-weight: 700; line-height: 1.3; margin: 0; padding-top: 4px;}
  .rm-brand span {color: #E4572E;}
  .rm-sub {color: #8B4513; margin-top: -4px; font-size: 1.02rem;}
  .rm-credit {color: #4169E1; font-size: 1.0rem; margin: 2px 0 6px;}
  .rm-verdict {font-size: 1.6rem; font-weight: 700; line-height: 1.25; margin: 2px 0 10px;}
  .ok {background:#dcfce7; color:#166534;} .warn {background:#fef3c7; color:#92400e;} .bad {background:#fee2e2; color:#991b1b;}
  .step-num {font-size: 2rem; font-weight: 700; color: #4169E1; line-height: 1;}
  .rule {border-top: 2px solid #15233a; margin: 0.4rem 0 1rem;}
  div[data-testid="stMetricValue"] {font-weight: 700;}
</style>
"""


def setup(site_name: str = APP_NAME) -> None:
    """Page config and CSS. Called once, from app.py."""
    st.set_page_config(page_title=site_name, layout="wide",
                       initial_sidebar_state="expanded")
    st.markdown(CSS, unsafe_allow_html=True)


def header(settings: dict) -> None:
    """Brand block: name with the last four letters in accent, tagline, credit."""
    brand = settings["site_name"]
    st.markdown(f"<div class='rm-brand'>{brand[:-4]}<span>{brand[-4:]}</span></div>",
                unsafe_allow_html=True)
    st.markdown(f"<div class='rm-sub'>{settings['tagline']} &middot; {settings['lab_name']}</div>",
                unsafe_allow_html=True)
    if settings.get("credit"):
        st.markdown(f"<div class='rm-credit'>{settings['credit']}</div>",
                    unsafe_allow_html=True)


def caption_row(pairs: list[tuple[str, str]]) -> None:
    """A single line of 'label value' pairs, like the summary bar on the pages."""
    st.markdown(
        " &nbsp;&nbsp;&nbsp; ".join(
            f"<span style='color:{INK_2}'>{k}</span> <b>{v}</b>" for k, v in pairs),
        unsafe_allow_html=True)


# -------------------------------------------------------------------------
# core/dynamics.py
# -------------------------------------------------------------------------
# Analytical chatter stability for milling.
#
# Zero-order frequency-domain solution (Altintas & Budak, CIRP Annals 1995):
# the time-varying directional coefficients are replaced by their average over one
# tooth period, which turns the stability problem into an eigenvalue problem that
# can be solved in closed form for each chatter frequency.
#
# Conventions used throughout:
#     phi_st, phi_ex   entry and exit angles, radians, measured from the +y axis
#                      in the usual milling convention
#     ap               axial depth of cut, mm
#     ae               radial width of cut, mm
#     n                spindle speed, rpm
#     Kt, Kr           tangential cutting force coefficient (N/mm^2) and the
#                      radial ratio Kr = Kn/Kt (dimensionless)
#
# The module is framework-free: import it from a notebook or a script.




# --------------------------------------------------------------------------
# Machine / tool dynamics
# --------------------------------------------------------------------------

@dataclass
class Mode:
    """One vibration mode of the tool-holder-spindle system in one direction."""
    fn_hz: float          # natural frequency
    zeta: float           # damping ratio (0.03 = 3%)
    k_n_m: float          # modal stiffness, N/m

    def frf(self, omega: np.ndarray) -> np.ndarray:
        """Receptance, m/N. omega in rad/s."""
        wn = 2 * np.pi * self.fn_hz
        r = omega / wn
        return 1.0 / (self.k_n_m * (1 - r ** 2 + 2j * self.zeta * r))


@dataclass
class ToolDynamics:
    """Modes in the feed (x) and normal (y) directions."""
    x_modes: list[Mode]
    y_modes: list[Mode]

    def phi_xx(self, omega):
        return sum(m.frf(omega) for m in self.x_modes)

    def phi_yy(self, omega):
        return sum(m.frf(omega) for m in self.y_modes)

    @property
    def frequencies(self) -> list[float]:
        return [m.fn_hz for m in self.x_modes + self.y_modes]


# Presets so the app is usable before a tap test. These are representative
# figures for the classes of tool named, not measurements of a specific setup.
PRESETS: dict[str, dict] = {
    "Slender carbide end mill, long overhang": dict(
        fn=820.0, zeta=0.035, k=8.0e6, note="10-12 mm end mill, 4-5×D overhang"),
    "Short carbide end mill, rigid holder": dict(
        fn=1450.0, zeta=0.04, k=3.5e7, note="10-12 mm end mill, 2×D overhang"),
    "Face mill on a stiff spindle": dict(
        fn=600.0, zeta=0.05, k=5.0e7, note="50-63 mm face mill, machining centre"),
    "Micro end mill (0.5-1 mm), high-speed spindle": dict(
        fn=6500.0, zeta=0.03, k=1.2e6, note="tool-dominated mode, very low stiffness"),
    "Thin-walled workpiece (part-dominated)": dict(
        fn=380.0, zeta=0.015, k=4.0e6, note="flexible part, lightly damped"),
}


def preset_dynamics(name: str) -> ToolDynamics:
    p = PRESETS[name]
    mode = lambda: Mode(p["fn"], p["zeta"], p["k"])
    return ToolDynamics([mode()], [mode()])


# --------------------------------------------------------------------------
# Cut geometry
# --------------------------------------------------------------------------

def engagement_angles(diameter_mm: float, ae_mm: float, direction: str) -> tuple[float, float]:
    """Entry and exit angles for up (conventional) or down (climb) milling."""
    ratio = np.clip(ae_mm / diameter_mm, 1e-6, 1.0)
    if direction.startswith("up") or direction.startswith("conv"):
        return 0.0, float(np.arccos(1 - 2 * ratio))
    return float(np.arccos(2 * ratio - 1)), float(np.pi)


def directional_coefficients(phi_st: float, phi_ex: float, Kr: float):
    """Average directional factors alpha_xx, alpha_xy, alpha_yx, alpha_yy.

    These are the integrals of the time-varying directional matrix over one
    tooth period, evaluated in closed form between the entry and exit angles.
    """
    def evaluate(f):
        return f(phi_ex) - f(phi_st)

    axx = 0.5 * evaluate(lambda p: np.cos(2 * p) - 2 * Kr * p + Kr * np.sin(2 * p))
    axy = 0.5 * evaluate(lambda p: -np.sin(2 * p) - 2 * p + Kr * np.cos(2 * p))
    ayx = 0.5 * evaluate(lambda p: -np.sin(2 * p) + 2 * p + Kr * np.cos(2 * p))
    ayy = 0.5 * evaluate(lambda p: -np.cos(2 * p) - 2 * Kr * p - Kr * np.sin(2 * p))
    return axx, axy, ayx, ayy


# --------------------------------------------------------------------------
# Stability lobes
# --------------------------------------------------------------------------

@dataclass
class StabilityResult:
    speeds_rpm: np.ndarray            # one row per lobe number
    depths_mm: np.ndarray             # matching limiting axial depths
    lobes: np.ndarray                 # lobe index for each point
    chatter_hz: np.ndarray            # chatter frequency at each point
    n_grid: np.ndarray = field(default_factory=lambda: np.empty(0))
    alim_grid: np.ndarray = field(default_factory=lambda: np.empty(0))
    n_reliable_min: float = 0.0
    """Below this speed the lobes are closer together than the speed grid can
    resolve, so the envelope there is aliasing rather than physics. Low speeds
    are also where process damping makes real cuts more stable than this model
    predicts, so both effects say the same thing: do not trust it down there."""

    def limit_at(self, n_rpm: float) -> float:
        """Limiting depth of cut at one spindle speed, mm."""
        if self.n_grid.size == 0:
            return float("nan")
        return float(np.interp(n_rpm, self.n_grid, self.alim_grid))


def stability_lobes(dyn: ToolDynamics, *, teeth: int, Kt: float, Kr: float,
                    phi_st: float, phi_ex: float, n_lobes: int = 12,
                    freq_points: int = 6000,
                    freq_span: tuple[float, float] | None = None,
                    n_range: tuple[float, float] = (500, 30000),
                    n_points: int = 1200) -> StabilityResult:
    """Sweep chatter frequency, solve for the limiting depth and the speeds."""
    fns = dyn.frequencies
    lo, hi = freq_span or (0.35 * min(fns), 2.2 * max(fns))
    fc = np.linspace(max(1.0, lo), hi, freq_points)
    omega = 2 * np.pi * fc

    Pxx = dyn.phi_xx(omega)
    Pyy = dyn.phi_yy(omega)
    axx, axy, ayx, ayy = directional_coefficients(phi_st, phi_ex, Kr)

    # a0 * L^2 + a1 * L + 1 = 0
    a0 = Pxx * Pyy * (axx * ayy - axy * ayx)
    a1 = axx * Pxx + ayy * Pyy
    disc = np.sqrt(np.where(np.abs(a0) > 0, a1 ** 2 - 4 * a0, a1 ** 2 + 0j))

    speeds, depths, lobe_ids, freqs = [], [], [], []
    grid = np.linspace(n_range[0], n_range[1], n_points)
    branch_curves: list[np.ndarray] = []

    for sign in (+1, -1):                    # both roots of the quadratic
        with np.errstate(divide="ignore", invalid="ignore"):
            L = np.where(np.abs(a0) > 1e-30, (-a1 + sign * disc) / (2 * a0), -1.0 / a1)
        LR, LI = np.real(L), np.imag(L)
        kappa = LI / LR
        # Kt in N/mm^2 and receptance in m/N: the 1e-3 converts the depth to mm
        alim = -2 * np.pi * LR * (1 + kappa ** 2) / (teeth * Kt) * 1e-3
        eps = np.pi - 2 * np.arctan(kappa)
        for k in range(n_lobes + 1):
            T = (eps + 2 * np.pi * k) / omega          # tooth period, s
            n = 60.0 / (teeth * T)
            ok = (alim > 0) & np.isfinite(alim) & (n > n_range[0]) & (n < n_range[1])
            if ok.sum() < 3:
                continue
            speeds.append(n[ok]); depths.append(alim[ok])
            lobe_ids.append(np.full(ok.sum(), k)); freqs.append(fc[ok])
            branch_curves.append(_branch_on_grid(n[ok], alim[ok], grid))

    n_all = np.concatenate(speeds) if speeds else np.empty(0)
    a_all = np.concatenate(depths) if depths else np.empty(0)
    k_all = np.concatenate(lobe_ids) if lobe_ids else np.empty(0)
    f_all = np.concatenate(freqs) if freqs else np.empty(0)

    # The usable boundary is the lowest branch at each speed. Each branch is
    # interpolated onto the grid over the span it actually covers, so a sparsely
    # sampled branch cannot punch single-cell holes in the envelope.
    if branch_curves:
        stack = np.vstack(branch_curves)
        with warnings.catch_warnings():       # columns no branch covers are all-NaN
            warnings.simplefilter("ignore", RuntimeWarning)
            env = np.nanmin(stack, axis=0)
        env = _fill_gaps(np.where(np.isfinite(env), env, np.inf))
    else:
        env = np.zeros(n_points)
    step = grid[1] - grid[0]
    fn_min = min(dyn.frequencies)
    reliable = float(np.sqrt(20 * step * 60 * fn_min / teeth))
    return StabilityResult(speeds_rpm=n_all, depths_mm=a_all, lobes=k_all,
                           chatter_hz=f_all, n_grid=grid, alim_grid=env,
                           n_reliable_min=min(reliable, grid[-1]))


def _branch_on_grid(n: np.ndarray, a: np.ndarray, grid: np.ndarray) -> np.ndarray:
    """One lobe branch resampled onto the speed grid, NaN outside its own span."""
    order = np.argsort(n)
    ns, as_ = n[order], a[order]
    # a branch can fold back on itself in speed; keep the lower depth per speed
    uniq, inv = np.unique(np.round(ns, 6), return_inverse=True)
    low = np.full(uniq.size, np.inf)
    np.minimum.at(low, inv, as_)
    out = np.interp(grid, uniq, low, left=np.nan, right=np.nan)
    return np.where((grid >= uniq[0]) & (grid <= uniq[-1]), out, np.nan)


def _fill_gaps(env: np.ndarray) -> np.ndarray:
    """Interpolate grid cells that no lobe point landed in."""
    finite = np.isfinite(env)
    if not finite.any():
        return np.zeros_like(env)
    idx = np.arange(len(env))
    return np.interp(idx, idx[finite], env[finite])


def chatter_frequency_at(res: StabilityResult, n_rpm: float) -> float:
    """Frequency the chatter would grow at, for the speed given."""
    if res.speeds_rpm.size == 0:
        return float("nan")
    near = np.abs(res.speeds_rpm - n_rpm) < max(25.0, 0.01 * n_rpm)
    if not near.any():
        near = np.abs(res.speeds_rpm - n_rpm) == np.abs(res.speeds_rpm - n_rpm).min()
    sel = np.argmin(res.depths_mm[near])
    return float(res.chatter_hz[near][sel])


# --------------------------------------------------------------------------
# Working with an operating point
# --------------------------------------------------------------------------

def tooth_passing_hz(n_rpm: float, teeth: int) -> float:
    return n_rpm * teeth / 60.0


def material_removal_rate(ap_mm: float, ae_mm: float, feed_mm_min: float) -> float:
    """MRR in mm^3/min."""
    return ap_mm * ae_mm * feed_mm_min


def stable_speed_suggestions(res: StabilityResult, ap_mm: float, n_rpm: float,
                             n_max: int = 3, margin: float = 1.2) -> list[dict]:
    """Speeds near the current one where the limit clears the depth being used.

    Returns the peak of each usable stability pocket, closest first.
    """
    n, a = res.n_grid, res.alim_grid
    usable = (a >= ap_mm * margin) & (n >= res.n_reliable_min)
    if not usable.any():
        return []
    # contiguous runs of usable speeds = stability pockets
    padded = np.r_[False, usable, False]
    starts = np.flatnonzero(~padded[:-1] & padded[1:])
    ends = np.flatnonzero(padded[:-1] & ~padded[1:]) - 1
    out = []
    step = n[1] - n[0]
    for s, e in zip(starts, ends):
        if e - s < 2:                       # ignore single-cell jitter
            continue
        best = s + int(np.argmax(a[s:e + 1]))
        nearest = int(np.clip(np.searchsorted(n, n_rpm), s, e))
        out.append({"speed_rpm": float(n[best]), "limit_mm": float(a[best]),
                    "nearest_rpm": float(n[nearest]),
                    "nearest_limit_mm": float(a[nearest]),
                    "from_rpm": float(n[s]), "to_rpm": float(n[e]),
                    "width_rpm": float(n[e] - n[s] + step),
                    "distance_rpm": float(abs(n[nearest] - n_rpm))})
    out.sort(key=lambda d: d["distance_rpm"])
    return out[:n_max]


# -------------------------------------------------------------------------
# core/roughness.py
# -------------------------------------------------------------------------
# Expected surface roughness from the cutting geometry.
#
# The geometric part is exact: it is the height of the material left between
# successive tool marks. The rest is honest correction factors, each one reported
# separately so you can see what the number is made of rather than trusting a
# single figure.
#
# Real Ra is almost always above the geometric value — tool wear, built-up edge,
# side flow, runout and residual vibration all add to it. A process factor of
# about 1.5 to 2.5 is typical for a well-behaved cut.



# ISO 1302 roughness grades, Ra in micrometres
ISO_GRADES = {"N1": 0.025, "N2": 0.05, "N3": 0.1, "N4": 0.2, "N5": 0.4, "N6": 0.8,
              "N7": 1.6, "N8": 3.2, "N9": 6.3, "N10": 12.5, "N11": 25.0, "N12": 50.0}

OPERATIONS = ["Face milling / turning (nose radius)",
              "Peripheral milling (flat end mill)",
              "Ball-nose finishing (stepover)"]


@dataclass
class RoughnessResult:
    ra_geometric_um: float
    ra_expected_um: float
    rz_geometric_um: float
    effective_feed_mm: float
    factors: dict[str, float] = field(default_factory=dict)
    notes: list[str] = field(default_factory=list)
    chatter_range_um: tuple[float, float] | None = None

    @property
    def grade(self) -> str:
        for name, value in ISO_GRADES.items():
            if self.ra_expected_um <= value:
                return name
        return "coarser than N12"


def effective_feed(fz_mm: float, teeth: int, runout_mm: float) -> tuple[float, float]:
    """Feed between consecutive marks once runout is accounted for.

    With no runout every tooth cuts the same chip and the marks are fz apart.
    Once the radial throw of one tooth exceeds the feed per tooth, that tooth
    does all the cutting and the marks open out towards the feed per revolution.
    """
    if runout_mm <= 0 or teeth <= 1:
        return fz_mm, 0.0
    share = float(min(1.0, runout_mm / max(fz_mm, 1e-9)))
    return fz_mm * (1 + share * (teeth - 1)), share


def roughness(operation: str, *, fz_mm: float, teeth: int, diameter_mm: float,
              nose_radius_mm: float = 0.8, stepover_mm: float = 0.5,
              runout_mm: float = 0.0, process_factor: float = 1.8,
              edge_radius_um: float | None = None,
              unstable: bool = False) -> RoughnessResult:
    f_eff, runout_share = effective_feed(fz_mm, teeth, runout_mm)
    notes: list[str] = []
    factors: dict[str, float] = {}

    if operation.startswith("Face"):
        rz = f_eff ** 2 / (8 * max(nose_radius_mm, 1e-6)) * 1e3     # mm -> um
        ra = f_eff ** 2 / (32 * max(nose_radius_mm, 1e-6)) * 1e3
        notes.append("Geometric part: marks left by the nose radius, "
                     "Rz = f²/(8r), Ra = f²/(32r).")
    elif operation.startswith("Peripheral"):
        R = max(diameter_mm / 2, 1e-6)
        rz = f_eff ** 2 / (8 * R) * 1e3
        ra = rz / 4
        notes.append("Geometric part: cusps left by the circular tooth path on the "
                     "wall, Rz ≈ fz²/(8R) with R the cutter radius.")
    else:
        R = max(diameter_mm / 2, 1e-6)
        h = R - np.sqrt(max(R ** 2 - (stepover_mm / 2) ** 2, 0.0))
        rz = h * 1e3
        ra = rz / 4
        notes.append("Geometric part: scallop height between passes, "
                     "h = R − √(R² − (ae/2)²). Stepover drives this, not feed.")

    ra_expected = ra
    if runout_share > 0:
        factors["runout"] = f_eff / max(fz_mm, 1e-9)
        notes.append(f"Runout of {runout_mm * 1000:.0f} µm opens the mark spacing from "
                     f"{fz_mm:.4f} to {f_eff:.4f} mm/mark.")

    # Minimum chip thickness: below roughly a quarter of the edge radius the
    # edge ploughs instead of cutting, and the finish degrades sharply. This
    # matters in micro-milling, where fz and the edge radius are comparable.
    if edge_radius_um:
        h_min_mm = 0.25 * edge_radius_um * 1e-3
        if fz_mm < h_min_mm:
            k = float(np.sqrt(h_min_mm / max(fz_mm, 1e-9)))
            factors["ploughing"] = k
            ra_expected *= k
            notes.append(
                f"Feed per tooth ({fz_mm * 1000:.1f} µm) is below the minimum chip "
                f"thickness (~{h_min_mm * 1000:.1f} µm for a {edge_radius_um:.0f} µm "
                "edge radius), so the edge ploughs and rubs. Heuristic penalty applied.")

    factors["process"] = process_factor
    ra_expected *= process_factor

    chatter_range = None
    if unstable:
        chatter_range = (ra_expected * 3, ra_expected * 10)
        notes.append("The cut is predicted to be unstable, so this figure is only a "
                     "floor: chatter marks set the finish instead of the feed marks. "
                     "Measured Ra under chatter is typically three to ten times the "
                     "stable value, with visible waviness.")

    return RoughnessResult(ra_geometric_um=float(ra), ra_expected_um=float(ra_expected),
                           rz_geometric_um=float(rz), effective_feed_mm=float(f_eff),
                           factors=factors, notes=notes, chatter_range_um=chatter_range)


def feed_for_target_ra(operation: str, target_ra_um: float, *, teeth: int,
                       diameter_mm: float, nose_radius_mm: float,
                       process_factor: float) -> float | None:
    """Feed per tooth that would just meet a target Ra, ignoring runout."""
    ra = target_ra_um / max(process_factor, 1e-6)
    if operation.startswith("Face"):
        return float(np.sqrt(ra * 32 * nose_radius_mm * 1e-3))
    if operation.startswith("Peripheral"):
        return float(np.sqrt(ra * 4 * 8 * (diameter_mm / 2) * 1e-3))
    return None            # ball-nose finish is set by stepover, not feed


def stepover_for_target_ra(target_ra_um: float, diameter_mm: float,
                           process_factor: float) -> float:
    """Stepover that would just meet a target Ra in ball-nose finishing."""
    R = diameter_mm / 2
    h = target_ra_um / max(process_factor, 1e-6) * 4 * 1e-3      # um -> mm
    h = min(h, R * 0.999)
    return float(2 * np.sqrt(max(R ** 2 - (R - h) ** 2, 0.0)))


# -------------------------------------------------------------------------
# core/recommend.py
# -------------------------------------------------------------------------
# Turn the stability and roughness results into a verdict and a set of moves.
#
# Every recommendation here is computed from the models — a suggested spindle
# speed comes from the stability pockets that were actually solved for, and a
# suggested feed comes from inverting the roughness model — rather than being a
# fixed list of machining advice.




@dataclass
class Action:
    change: str
    detail: str
    gain: str = ""


@dataclass
class Assessment:
    stable: bool
    margin: float                 # ap_limit / ap, above 1 is stable
    ap_limit_mm: float
    chatter_hz: float | None
    tooth_passing_hz: float
    meets_target: bool | None
    headline: str
    state_reason: str
    finish_reason: str
    actions: list[Action] = field(default_factory=list)
    mrr_mm3_min: float = 0.0


def assess(*, res: dy.StabilityResult, ap_mm: float, ae_mm: float, n_rpm: float,
           teeth: int, fz_mm: float, feed_mm_min: float,
           rough: rg.RoughnessResult, target_ra_um: float | None,
           operation: str, diameter_mm: float, nose_radius_mm: float,
           process_factor: float, dyn: dy.ToolDynamics, Kt: float, Kr: float,
           direction: str) -> Assessment:
    ap_limit = res.limit_at(n_rpm)
    stable = ap_mm <= ap_limit
    margin = ap_limit / max(ap_mm, 1e-9)
    tpf = dy.tooth_passing_hz(n_rpm, teeth)
    fc = None if stable else dy.chatter_frequency_at(res, n_rpm)

    if stable:
        state_reason = (
            f"At {n_rpm:,.0f} rpm the limiting axial depth is {ap_limit:.2f} mm and you "
            f"are cutting {ap_mm:.2f} mm, so the cut sits {margin:.1f}× inside the "
            "stability boundary.")
        if margin < 1.3:
            state_reason += (" That is a thin margin — a worn tool or a softer clamping "
                             "will push it over.")
    else:
        state_reason = (
            f"At {n_rpm:,.0f} rpm the limiting axial depth is {ap_limit:.2f} mm but you "
            f"are cutting {ap_mm:.2f} mm, which is {1 / max(margin, 1e-9):.1f}× the limit. "
            f"Regenerative chatter is predicted at about {fc:,.0f} Hz, against a tooth "
            f"passing frequency of {tpf:,.0f} Hz.")

    meets = None if target_ra_um is None else rough.ra_expected_um <= target_ra_um
    if target_ra_um is None:
        finish_reason = (f"Expected Ra is about {rough.ra_expected_um:.2f} µm "
                         f"({rough.grade}), from a geometric {rough.ra_geometric_um:.2f} µm.")
    elif meets:
        finish_reason = (f"Expected Ra {rough.ra_expected_um:.2f} µm meets the "
                         f"{target_ra_um:.2f} µm target with room to spare.")
    else:
        finish_reason = (f"Expected Ra {rough.ra_expected_um:.2f} µm misses the "
                         f"{target_ra_um:.2f} µm target by "
                         f"{rough.ra_expected_um / target_ra_um:.1f}×.")

    quality = "bad" if meets is False else "good"
    headline = {
        (True, "good"): "Stable cut, finish within target",
        (True, "bad"): "Stable cut, but the finish misses the target",
        (False, "good"): "Chatter predicted — the finish figure will not hold",
        (False, "bad"): "Chatter predicted, and the finish misses the target",
    }[(stable, quality)]

    actions = _actions(res=res, ap_mm=ap_mm, ae_mm=ae_mm, n_rpm=n_rpm, teeth=teeth,
                       fz_mm=fz_mm, stable=stable, rough=rough,
                       target_ra_um=target_ra_um, operation=operation,
                       diameter_mm=diameter_mm, nose_radius_mm=nose_radius_mm,
                       process_factor=process_factor, dyn=dyn, Kt=Kt, Kr=Kr,
                       direction=direction, feed_mm_min=feed_mm_min)

    return Assessment(stable=stable, margin=float(margin), ap_limit_mm=float(ap_limit),
                      chatter_hz=fc, tooth_passing_hz=tpf, meets_target=meets,
                      headline=headline, state_reason=state_reason,
                      finish_reason=finish_reason, actions=actions,
                      mrr_mm3_min=dy.material_removal_rate(ap_mm, ae_mm, feed_mm_min))


def _actions(*, res, ap_mm, ae_mm, n_rpm, teeth, fz_mm, stable, rough, target_ra_um,
             operation, diameter_mm, nose_radius_mm, process_factor, dyn, Kt, Kr,
             direction, feed_mm_min) -> list[Action]:
    out: list[Action] = []

    if not stable:
        pockets = dy.stable_speed_suggestions(res, ap_mm, n_rpm)
        for p in pockets[:2]:
            new_feed = p["speed_rpm"] * teeth * fz_mm
            out.append(Action(
                change=f"Move the spindle to {p['speed_rpm']:,.0f} rpm",
                detail=(f"That pocket runs from {p['from_rpm']:,.0f} to "
                        f"{p['to_rpm']:,.0f} rpm and allows {p['limit_mm']:.2f} mm "
                        f"axial depth at its peak, against the {ap_mm:.2f} mm you need. "
                        f"Keep the feed per tooth: feed becomes {new_feed:,.0f} mm/min."),
                gain=f"{p['width_rpm']:,.0f} rpm wide, so it tolerates speed drift"))
        if not pockets:
            out.append(Action(
                change="No stable pocket at this depth anywhere in the speed range",
                detail="The depth of cut is above the critical limit at every speed, so "
                       "no choice of spindle speed will fix it on its own.",
                gain=""))

        out.append(Action(
            change=f"Reduce axial depth to {res.limit_at(n_rpm) / 1.3:.2f} mm at this speed",
            detail=(f"The limit here is {res.limit_at(n_rpm):.2f} mm; taking 30% below it "
                    "leaves margin for tool wear. Two passes at that depth beat one "
                    "chattered pass."),
            gain=f"Keeps {n_rpm:,.0f} rpm if the speed is fixed by the setup"))

        lighter = _limit_at_lower_immersion(dyn, teeth, Kt, Kr, diameter_mm, ae_mm,
                                            direction, n_rpm)
        if lighter and lighter[1] > res.limit_at(n_rpm) * 1.15:
            out.append(Action(
                change=f"Reduce radial engagement to {lighter[0]:.2f} mm",
                detail=(f"Lighter radial immersion raises the limit at this speed from "
                        f"{res.limit_at(n_rpm):.2f} to {lighter[1]:.2f} mm, because the "
                        "tooth spends less time in the cut."),
                gain="Often recovers the lost material rate through higher feed"))

        out.append(Action(
            change="If the speed is fixed, change the cutter or add damping",
            detail="A variable-pitch or variable-helix cutter breaks the regenerative "
                   "phasing that this analysis assumes. A shorter overhang raises the "
                   "natural frequency and the stiffness, which lifts the whole diagram.",
            gain="Shifts the boundary rather than working around it"))

    # Finish
    if target_ra_um is not None and rough.ra_expected_um > target_ra_um:
        if operation.startswith("Ball"):
            ae_new = rg.stepover_for_target_ra(target_ra_um, diameter_mm, process_factor)
            out.append(Action(
                change=f"Reduce the stepover to about {ae_new:.3f} mm",
                detail="Ball-nose finish is set by the scallop between passes, so "
                       "stepover is the lever, not feed.",
                gain=f"Roughly {ae_mm / max(ae_new, 1e-6):.1f}× more passes"))
        else:
            fz_new = rg.feed_for_target_ra(operation, target_ra_um, teeth=teeth,
                                           diameter_mm=diameter_mm,
                                           nose_radius_mm=nose_radius_mm,
                                           process_factor=process_factor)
            if fz_new:
                out.append(Action(
                    change=f"Reduce feed per tooth to about {fz_new:.4f} mm",
                    detail=(f"Ra scales with the square of the feed, so going from "
                            f"{fz_mm:.4f} to {fz_new:.4f} mm/tooth brings the expected "
                            f"value to the {target_ra_um:.2f} µm target. Stability is "
                            "unaffected: the lobe diagram does not depend on feed."),
                    gain=f"Feed rate becomes {n_rpm * teeth * fz_new:,.0f} mm/min"))
        if operation.startswith("Face"):
            r_new = nose_radius_mm * (rough.ra_expected_um / target_ra_um)
            out.append(Action(
                change=f"Or fit a larger nose radius, about {r_new:.2f} mm",
                detail="Ra falls inversely with nose radius, so a bigger radius or a "
                       "wiper insert meets the target without losing feed rate.",
                gain="Keeps the material removal rate"))

    if "ploughing" in rough.factors:
        out.append(Action(
            change="Raise feed per tooth above the minimum chip thickness",
            detail="Below roughly a quarter of the edge radius the edge rubs rather "
                   "than cuts, which raises roughness, forces and tool wear at the same "
                   "time. Counter-intuitively, feeding harder gives a better finish here.",
            gain="Also reduces the risk of tool breakage in micro-milling"))

    if "runout" in rough.factors:
        out.append(Action(
            change="Check and correct tool runout",
            detail=(f"Runout is spreading the marks to {rough.effective_feed_mm:.4f} mm "
                    f"instead of {fz_mm:.4f} mm, which is the same as multiplying the "
                    "feed. Re-seat the tool, clean the taper, or measure TIR with a dial "
                    "indicator."),
            gain="Recovers finish without changing any cutting parameter"))

    if stable and (target_ra_um is None or rough.ra_expected_um <= target_ra_um):
        headroom = res.limit_at(n_rpm) / max(ap_mm, 1e-9)
        out.append(Action(
            change=f"There is headroom: the limit here is {res.limit_at(n_rpm):.2f} mm",
            detail=(f"You are using {ap_mm:.2f} mm, which is {headroom:.1f}× inside the "
                    "boundary. Raising the depth in steps, checking the surface each "
                    "time, converts that margin into material rate."),
            gain=f"Up to {(headroom / 1.3):.1f}× the current MRR while keeping margin"))

    return out


def _limit_at_lower_immersion(dyn, teeth, Kt, Kr, diameter_mm, ae_mm, direction,
                              n_rpm) -> tuple[float, float] | None:
    """Re-solve the diagram at half the radial width and report the new limit."""
    ae_new = max(ae_mm / 2, diameter_mm * 0.02)
    if ae_new >= ae_mm:
        return None
    st, ex = dy.engagement_angles(diameter_mm, ae_new, direction)
    res = dy.stability_lobes(dyn, teeth=teeth, Kt=Kt, Kr=Kr, phi_st=st, phi_ex=ex,
                             freq_points=2500, n_points=800,
                             n_range=(max(200, n_rpm * 0.2), n_rpm * 3))
    return ae_new, res.limit_at(n_rpm)


# -------------------------------------------------------------------------
# core/inputs.py
# -------------------------------------------------------------------------
# The sidebar form, in one place so every page asks for the same things.
#
# Cutting force coefficients are order-of-magnitude values for the material
# groups named. They vary with tool geometry, coating, chip thickness and speed,
# so replace them with your own calibrated values when you have them.




MATERIALS = {
    "Aluminium 6061 / 7075": dict(Kt=750.0, Kr=0.30),
    "Brass / bronze": dict(Kt=700.0, Kr=0.28),
    "Cast iron": dict(Kt=1100.0, Kr=0.30),
    "Mild steel 1018 / 1045": dict(Kt=1800.0, Kr=0.35),
    "Alloy steel 4140, hardened": dict(Kt=2300.0, Kr=0.38),
    "Stainless 304 / 316": dict(Kt=2000.0, Kr=0.40),
    "Ti-6Al-4V": dict(Kt=1700.0, Kr=0.35),
    "Inconel 718": dict(Kt=2600.0, Kr=0.42),
    "Custom": dict(Kt=1500.0, Kr=0.35),
}


@dataclass
class Setup:
    operation: str
    diameter_mm: float
    teeth: int
    nose_radius_mm: float
    edge_radius_um: float | None
    ae_mm: float
    ap_mm: float
    n_rpm: float
    fz_mm: float
    direction: str
    Kt: float
    Kr: float
    dyn: dy.ToolDynamics
    runout_mm: float
    process_factor: float
    target_ra_um: float | None
    stepover_mm: float

    @property
    def feed_mm_min(self) -> float:
        return self.n_rpm * self.teeth * self.fz_mm

    @property
    def cutting_speed_m_min(self) -> float:
        return 3.141592653589793 * self.diameter_mm * self.n_rpm / 1000.0

    @property
    def angles(self):
        return dy.engagement_angles(self.diameter_mm, self.ae_mm, self.direction)


def sidebar() -> Setup:
    with st.sidebar:
        st.header("Operation")
        operation = st.selectbox("Type", rg.OPERATIONS)

        st.header("Tool")
        c1, c2 = st.columns(2)
        diameter = c1.number_input("Diameter (mm)", 0.05, 300.0, 12.0, 0.5)
        teeth = int(c2.number_input("Teeth", 1, 20, 4, 1))
        nose = st.number_input("Nose radius (mm)", 0.0, 10.0, 0.8, 0.1,
                               help="Used by the roughness model for face milling "
                                    "and turning.")
        micro = st.checkbox("Micro tool — account for minimum chip thickness",
                            value=diameter < 2.0)
        edge_radius = st.number_input("Cutting-edge radius (µm)", 0.1, 50.0, 2.0, 0.5) \
            if micro else None

        st.header("Cut")
        c1, c2 = st.columns(2)
        ap = c1.number_input("Axial depth ap (mm)", 0.001, 100.0, 4.0, 0.5)
        ae = c2.number_input("Radial width ae (mm)", 0.001, 300.0, 3.0, 0.5)
        if ae > diameter:
            st.warning("Radial width is larger than the cutter; treating it as slotting.")
            ae = diameter
        c1, c2 = st.columns(2)
        n_rpm = c1.number_input("Spindle speed (rpm)", 10.0, 200000.0, 5000.0, 100.0)
        fz = c2.number_input("Feed per tooth (mm)", 0.00005, 2.0, 0.06, 0.01,
                             format="%.5f")
        direction = st.radio("Milling direction", ["down (climb)", "up (conventional)"],
                             horizontal=True)
        stepover = st.number_input("Stepover for finishing (mm)", 0.001, 50.0, 0.5, 0.1) \
            if operation.startswith("Ball") else 0.5

        st.header("Workpiece")
        mat = st.selectbox("Material", list(MATERIALS))
        d = MATERIALS[mat]
        c1, c2 = st.columns(2)
        Kt = c1.number_input("Kt (N/mm²)", 100.0, 6000.0, float(d["Kt"]), 50.0)
        Kr = c2.number_input("Kr = Kn/Kt", 0.0, 1.5, float(d["Kr"]), 0.05)

        st.header("Dynamics")
        preset = st.selectbox("Tap-test data", list(dy.PRESETS) + ["Enter my own"])
        if preset == "Enter my own":
            st.caption("From a tap test: natural frequency, damping ratio and modal "
                       "stiffness of the dominant mode in each direction.")
            c1, c2, c3 = st.columns(3)
            fx = c1.number_input("fn x (Hz)", 10.0, 50000.0, 800.0, 10.0)
            zx = c2.number_input("ζ x", 0.001, 0.5, 0.035, 0.005, format="%.3f")
            kx = c3.number_input("k x (N/m)", 1e4, 1e9, 1.0e7, 1e6, format="%.3g")
            same = st.checkbox("y direction is the same", value=True)
            if same:
                fy, zy, ky = fx, zx, kx
            else:
                c1, c2, c3 = st.columns(3)
                fy = c1.number_input("fn y (Hz)", 10.0, 50000.0, 900.0, 10.0)
                zy = c2.number_input("ζ y", 0.001, 0.5, 0.035, 0.005, format="%.3f")
                ky = c3.number_input("k y (N/m)", 1e4, 1e9, 1.2e7, 1e6, format="%.3g")
            dyn = dy.ToolDynamics([dy.Mode(fx, zx, kx)], [dy.Mode(fy, zy, ky)])
        else:
            st.caption(dy.PRESETS[preset]["note"] + " — representative values, "
                       "not a measurement of your machine.")
            dyn = dy.preset_dynamics(preset)

        st.header("Finish")
        runout = st.number_input("Tool runout, TIR (µm)", 0.0, 500.0, 0.0, 1.0) / 1000.0
        factor = st.slider("Process factor", 1.0, 3.5, 1.8, 0.1,
                           help="How much above the geometric value real Ra lands. "
                                "1.5–2.5 is typical for a healthy cut.")
        use_target = st.checkbox("I have a target Ra", value=True)
        target = st.number_input("Target Ra (µm)", 0.01, 50.0, 1.6, 0.1) \
            if use_target else None

    return Setup(operation=operation, diameter_mm=diameter, teeth=teeth,
                 nose_radius_mm=nose, edge_radius_um=edge_radius, ae_mm=ae, ap_mm=ap,
                 n_rpm=n_rpm, fz_mm=fz, direction="down" if direction.startswith("down")
                 else "up", Kt=Kt, Kr=Kr, dyn=dyn, runout_mm=runout,
                 process_factor=factor, target_ra_um=target, stepover_mm=stepover)


@st.cache_data(show_spinner=False)
def solve(dyn_key_: tuple, teeth: int, Kt: float, Kr: float, phi: tuple[float, float],
          n_range: tuple[float, float], _dyn: dy.ToolDynamics) -> dy.StabilityResult:
    """Cached stability solve.

    dyn_key_ carries the modal numbers so the cache sees changes in tool dynamics;
    _dyn (leading underscore) is the unhashable object and is skipped by the cache.
    """
    return dy.stability_lobes(_dyn, teeth=teeth, Kt=Kt, Kr=Kr,
                              phi_st=phi[0], phi_ex=phi[1], n_range=n_range)


def dyn_key(dyn: dy.ToolDynamics) -> tuple:
    return tuple((m.fn_hz, m.zeta, m.k_n_m) for m in dyn.x_modes + dyn.y_modes)


def speed_range(s: Setup) -> tuple[float, float]:
    top = max(s.n_rpm * 2.5, max(m.fn_hz for m in s.dyn.x_modes) * 60 / s.teeth * 1.5)
    return (max(100.0, s.n_rpm * 0.15), float(min(top, 300000)))


# -------------------------------------------------------------------------
# views/predict.py
# -------------------------------------------------------------------------
# Predict the outcome of one cutting condition.




def render_predict(s, res) -> None:
    """One tab: verdict, lobe diagram, roughness breakdown and what to change."""
    phi = s.angles
    rough = rg.roughness(s.operation, fz_mm=s.fz_mm, teeth=s.teeth,
                         diameter_mm=s.diameter_mm, nose_radius_mm=s.nose_radius_mm,
                         stepover_mm=s.stepover_mm, runout_mm=s.runout_mm,
                         process_factor=s.process_factor, edge_radius_um=s.edge_radius_um,
                         unstable=s.ap_mm > res.limit_at(s.n_rpm))

    a = rc.assess(res=res, ap_mm=s.ap_mm, ae_mm=s.ae_mm, n_rpm=s.n_rpm, teeth=s.teeth,
                  fz_mm=s.fz_mm, feed_mm_min=s.feed_mm_min, rough=rough,
                  target_ra_um=s.target_ra_um, operation=s.operation,
                  diameter_mm=s.diameter_mm, nose_radius_mm=s.nose_radius_mm,
                  process_factor=s.process_factor, dyn=s.dyn, Kt=s.Kt, Kr=s.Kr,
                  direction=s.direction)

    # ---------------------------------------------------------------- verdict
    colour = theme.GOOD if (a.stable and a.meets_target is not False) else theme.BAD
    st.markdown(f"<p class='rm-verdict' style='color:{colour}'>{a.headline}</p>",
                unsafe_allow_html=True)

    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Process state", "Chatter" if not a.stable else "Stable",
              f"{a.margin:.2f}× the limit" if a.stable else f"{1 / a.margin:.2f}× over",
              delta_color="normal" if a.stable else "inverse")
    m2.metric("Limiting depth here", f"{a.ap_limit_mm:.2f} mm", f"using {s.ap_mm:.2f} mm")
    m3.metric("Expected Ra", f"{rough.ra_expected_um:.2f} µm", rough.grade)
    mrr_txt = (f"{a.mrr_mm3_min / 1000:,.1f}k" if a.mrr_mm3_min >= 10_000
               else f"{a.mrr_mm3_min:,.0f}")
    m4.metric("Removal rate (mm³/min)", mrr_txt, f"{s.feed_mm_min:,.0f} mm/min feed")

    st.write(a.state_reason)
    st.write(a.finish_reason)
    theme.caption_row([
        ("Cutting speed", f"{s.cutting_speed_m_min:,.0f} m/min"),
        ("Tooth passing", f"{a.tooth_passing_hz:,.0f} Hz"),
        ("Chatter frequency", f"{a.chatter_hz:,.0f} Hz" if a.chatter_hz else "—"),
        ("Immersion", f"{s.ae_mm / s.diameter_mm * 100:.0f}% ({s.direction})"),
        ("Engagement", f"{np.degrees(phi[0]):.0f}° to {np.degrees(phi[1]):.0f}°"),
    ])
    st.write("")

    tab_sld, tab_ra, tab_act, tab_num = st.tabs(
        ["Stability diagram", "Roughness", "What to change", "Numbers"])

    # ---------------------------------------------------------------- lobes
    with tab_sld:
        fig = go.Figure()
        top = max(s.ap_mm * 2.5, float(np.median(res.alim_grid)) * 3.0)
        fig.add_scatter(x=res.n_grid, y=np.minimum(res.alim_grid, top * 1.5),
                        name="Stability limit", line=dict(color=theme.SIGNAL, width=2),
                        fill="tozeroy", fillcolor="rgba(36,81,214,0.08)")
        fig.add_scatter(x=[s.n_rpm], y=[s.ap_mm], mode="markers+text",
                        name="Your cut", text=["your cut"], textposition="top center",
                        marker=dict(size=14, symbol="x-thin",
                                    line=dict(width=3, color=theme.BAD if not a.stable
                                              else theme.GOOD),
                                    color=theme.BAD if not a.stable else theme.GOOD))
        # Suggested pockets are only useful when the current point fails; drawing
        # them on a stable cut just crowds the operating-point marker.
        for p in ([] if a.stable
                  else dy.stable_speed_suggestions(res, s.ap_mm, s.n_rpm, n_max=3)):
            fig.add_scatter(x=[p["speed_rpm"]], y=[s.ap_mm], mode="markers",
                            name=f"{p['speed_rpm']:,.0f} rpm pocket",
                            marker=dict(size=11, symbol="circle-open",
                                        line=dict(width=2.5), color=theme.DETAIL))
        if res.n_reliable_min > res.n_grid[0]:
            fig.add_vrect(x0=res.n_grid[0], x1=res.n_reliable_min,
                          fillcolor="rgba(21,35,58,0.12)", line_width=0,
                          annotation_text="lobes not resolved", annotation_position="top left")
        fig.update_layout(height=470, xaxis_title="Spindle speed (rpm)",
                          yaxis_title="Axial depth of cut ap (mm)",
                          yaxis_range=[0, max(top, s.ap_mm * 1.6)])
        st.plotly_chart(fig, width="stretch")
        st.caption("Below the curve the cut is stable. The pockets are the speeds where the "
                   "tooth passing frequency and its harmonics line up with the dominant mode, "
                   "so the regenerative effect cancels. Zero-order analytical solution "
                   "(Altintas & Budak), which assumes a rigid, constant-speed spindle and "
                   "linear cutting force coefficients. Process damping, which makes low-speed cuts "
                   "more stable than the diagram suggests, is not modelled.")

    # ---------------------------------------------------------------- roughness
    with tab_ra:
        left, right = st.columns([3, 2], gap="medium")
        with left:
            if s.operation.startswith("Ball"):
                x = np.linspace(s.stepover_mm * 0.2, s.stepover_mm * 2.5, 120)
                ys = [rg.roughness(s.operation, fz_mm=s.fz_mm, teeth=s.teeth,
                                   diameter_mm=s.diameter_mm, stepover_mm=v,
                                   process_factor=s.process_factor).ra_expected_um for v in x]
                xt, here = "Stepover (mm)", s.stepover_mm
            else:
                x = np.linspace(max(s.fz_mm * 0.15, 1e-5), s.fz_mm * 2.5, 120)
                ys = [rg.roughness(s.operation, fz_mm=v, teeth=s.teeth,
                                   diameter_mm=s.diameter_mm,
                                   nose_radius_mm=s.nose_radius_mm,
                                   runout_mm=s.runout_mm, process_factor=s.process_factor,
                                   edge_radius_um=s.edge_radius_um).ra_expected_um for v in x]
                xt, here = "Feed per tooth (mm)", s.fz_mm
            fig = go.Figure()
            fig.add_scatter(x=x, y=ys, name="Expected Ra",
                            line=dict(color=theme.SIGNAL, width=2))
            fig.add_scatter(x=[here], y=[rough.ra_expected_um], mode="markers",
                            name="Your setting", marker=dict(size=12, color=theme.INK))
            if s.target_ra_um:
                fig.add_hline(y=s.target_ra_um, line=dict(color=theme.DETAIL, dash="dash"),
                              annotation_text=f"target {s.target_ra_um:g} µm")
            fig.update_layout(height=400, xaxis_title=xt, yaxis_title="Ra (µm)")
            st.plotly_chart(fig, width="stretch")
        with right:
            st.markdown("**How the number is built**")
            rows = [("Geometric Ra", f"{rough.ra_geometric_um:.3f} µm"),
                    ("Geometric Rz", f"{rough.rz_geometric_um:.3f} µm"),
                    ("Mark spacing used", f"{rough.effective_feed_mm:.4f} mm")]
            rows += [(f"× {k}", f"{v:.2f}") for k, v in rough.factors.items()]
            rows.append(("Expected Ra", f"{rough.ra_expected_um:.3f} µm ({rough.grade})"))
            if rough.chatter_range_um:
                rows.append(("Under chatter",
                             f"{rough.chatter_range_um[0]:.1f}–{rough.chatter_range_um[1]:.1f} µm"))
            st.dataframe(pd.DataFrame(rows, columns=["", "Value"]), hide_index=True,
                         width="stretch")
        for note in rough.notes:
            st.caption(note)

    # ---------------------------------------------------------------- actions
    with tab_act:
        if not a.actions:
            st.success("Nothing to change — the condition is stable and meets the target.")
        for act in a.actions:
            with st.container(border=True):
                st.markdown(f"**{act.change}**")
                st.write(act.detail)
                if act.gain:
                    st.caption(act.gain)

    # ---------------------------------------------------------------- numbers
    with tab_num:
        modes = [("x", m) for m in s.dyn.x_modes] + [("y", m) for m in s.dyn.y_modes]
        st.dataframe(pd.DataFrame(
            [{"direction": d, "fn (Hz)": m.fn_hz, "ζ": m.zeta, "k (N/m)": m.k_n_m}
             for d, m in modes]), hide_index=True, width="stretch")
        axx, axy, ayx, ayy = dy.directional_coefficients(phi[0], phi[1], s.Kr)
        st.dataframe(pd.DataFrame([{
            "Kt (N/mm²)": s.Kt, "Kr": s.Kr, "teeth": s.teeth,
            "φ entry (°)": np.degrees(phi[0]), "φ exit (°)": np.degrees(phi[1]),
            "αxx": axx, "αxy": axy, "αyx": ayx, "αyy": ayy,
            "critical ap (mm)": float(np.min(res.alim_grid)),
            "ap limit here (mm)": a.ap_limit_mm,
        }]).T.rename(columns={0: "value"}), width="stretch")
        summary = pd.DataFrame([{
            "operation": s.operation, "D (mm)": s.diameter_mm, "teeth": s.teeth,
            "n (rpm)": s.n_rpm, "fz (mm)": s.fz_mm, "ap (mm)": s.ap_mm, "ae (mm)": s.ae_mm,
            "direction": s.direction, "feed (mm/min)": s.feed_mm_min,
            "vc (m/min)": s.cutting_speed_m_min, "ap limit (mm)": a.ap_limit_mm,
            "state": "chatter" if not a.stable else "stable", "margin": a.margin,
            "Ra expected (um)": rough.ra_expected_um, "grade": rough.grade,
            "MRR (mm3/min)": a.mrr_mm3_min}])
        st.download_button("Download this case as CSV", summary.to_csv(index=False).encode(),
                           file_name="rajmill_case.csv", mime="text/csv")


# -------------------------------------------------------------------------
# views/process_map.py
# -------------------------------------------------------------------------
# Sweep speed and depth to find the most productive stable condition.




def render_process_map(s, res) -> None:
    st.caption("The same model swept over a range of speeds and depths, so you can see "
               "where the productive stable islands are instead of testing one point at "
               "a time.")

    c1, c2, c3 = st.columns(3)
    n_lo = c1.number_input("Speed from (rpm)", 100.0, 200000.0,
                           float(min(max(500.0, s.n_rpm * 0.3), 200000.0)), 100.0)
    n_hi = c2.number_input("Speed to (rpm)", 200.0, 300000.0,
                           float(min(max(s.n_rpm * 2.2, 200.0), 300000.0)), 100.0)
    ap_hi = c3.number_input("Depth to (mm)", 0.05, 200.0,
                            float(min(max(s.ap_mm * 2, 1.0), 200.0)), 0.5)

    n_axis = np.linspace(n_lo, max(n_hi, n_lo + 100), 240)
    ap_axis = np.linspace(0.02, ap_hi, 160)
    limit = np.array([res.limit_at(n) for n in n_axis])
    margin = limit[None, :] / ap_axis[:, None]           # >1 is stable

    mrr = np.outer(ap_axis, np.ones_like(n_axis)) * s.ae_mm * (n_axis * s.teeth * s.fz_mm)
    safe = (margin >= 1.3) & (n_axis[None, :] >= res.n_reliable_min)
    best_mrr = float(np.max(np.where(safe, mrr, 0)))
    bi = np.unravel_index(int(np.argmax(np.where(safe, mrr, 0))), mrr.shape)

    fig = go.Figure()
    fig.add_heatmap(x=n_axis, y=ap_axis, z=np.clip(margin, 0, 3),
                    colorscale=[[0.0, "#f6dcd9"], [0.33, "#f1b9b2"], [0.333, "#dfe9f7"],
                                [0.66, "#9fb4ea"], [1.0, "#2451d6"]],
                    colorbar=dict(title="ap limit / ap"), zmin=0, zmax=3)
    fig.add_contour(x=n_axis, y=ap_axis, z=margin, contours=dict(start=1, end=1, size=0,
                    coloring="none", showlabels=False),
                    line=dict(color=theme.INK, width=2), showscale=False, name="boundary")
    fig.add_scatter(x=[s.n_rpm], y=[s.ap_mm], mode="markers+text", text=["your cut"],
                    textposition="top center", name="your cut",
                    marker=dict(size=13, symbol="x-thin", line=dict(width=3, color=theme.INK),
                                color=theme.INK))
    if best_mrr > 0:
        fig.add_scatter(x=[n_axis[bi[1]]], y=[ap_axis[bi[0]]], mode="markers+text",
                        text=["best MRR"], textposition="bottom center", name="best MRR",
                        marker=dict(size=13, symbol="star", color=theme.DETAIL))
    if res.n_reliable_min > n_axis[0]:
        fig.add_vrect(x0=n_axis[0], x1=min(res.n_reliable_min, n_axis[-1]),
                      fillcolor="rgba(21,35,58,0.12)", line_width=0,
                      annotation_text="lobes not resolved", annotation_position="top left")
    fig.update_layout(height=520, xaxis_title="Spindle speed (rpm)",
                      yaxis_title="Axial depth ap (mm)")
    st.plotly_chart(fig, width="stretch")
    if res.n_reliable_min > n_axis[0]:
        st.caption(f"Below about {res.n_reliable_min:,.0f} rpm the lobes are packed closer "
                   "than the speed grid resolves, so that band is greyed out. Real cuts down "
                   "there are also more stable than this model says, because process damping "
                   "from the flank rubbing against the wavy surface is not included.")

    if best_mrr > 0:
        now = s.ap_mm * s.ae_mm * s.feed_mm_min
        st.success(
            f"Best stable point in this window: {n_axis[bi[1]]:,.0f} rpm at "
            f"{ap_axis[bi[0]]:.2f} mm depth, keeping a 1.3× margin. That is "
            f"{best_mrr:,.0f} mm³/min against {now:,.0f} mm³/min at your current setting "
            f"({best_mrr / max(now, 1e-9):.1f}×).")
    else:
        st.warning("No point in this window keeps a 1.3× margin. Widen the speed range, "
                   "or reduce the radial engagement in the sidebar.")

    st.subheader("Candidate conditions")
    st.caption("Speeds at the peak of each stability pocket, with the finish each would "
               "give at your current feed per tooth.")
    rows = []
    for p in dy.stable_speed_suggestions(res, s.ap_mm, s.n_rpm, n_max=8, margin=1.0):
        r = rg.roughness(s.operation, fz_mm=s.fz_mm, teeth=s.teeth,
                         diameter_mm=s.diameter_mm, nose_radius_mm=s.nose_radius_mm,
                         stepover_mm=s.stepover_mm, runout_mm=s.runout_mm,
                         process_factor=s.process_factor, edge_radius_um=s.edge_radius_um)
        feed = p["speed_rpm"] * s.teeth * s.fz_mm
        rows.append({"speed (rpm)": round(p["speed_rpm"]),
                     "pocket width (rpm)": round(p["width_rpm"]),
                     "ap limit (mm)": round(p["limit_mm"], 2),
                     "max ap at 1.3× margin (mm)": round(p["limit_mm"] / 1.3, 2),
                     "feed (mm/min)": round(feed),
                     "MRR at your ap (mm³/min)": round(s.ap_mm * s.ae_mm * feed),
                     "Ra (µm)": round(r.ra_expected_um, 2)})
    if rows:
        df = pd.DataFrame(rows).sort_values("speed (rpm)")
        st.dataframe(df, hide_index=True, width="stretch")
        st.download_button("Download candidates as CSV", df.to_csv(index=False).encode(),
                           file_name="rajmill_candidates.csv", mime="text/csv")
    else:
        st.info("No stability pocket clears the current depth of cut in the solved speed "
                "range.")


# -------------------------------------------------------------------------
# views/how_it_works.py
# -------------------------------------------------------------------------
# What the app does with your numbers, and where it stops being trustworthy.


STEPS = [
    ("Tool dynamics",
     "Natural frequency, damping ratio and modal stiffness in the feed and normal "
     "directions, from your tap test or from one of the presets."),
    ("Stability limit",
     "The directional coefficients are averaged over one tooth period, which turns the "
     "delay-differential problem into a quadratic eigenvalue problem. Solving it at each "
     "chatter frequency gives the limiting axial depth and the spindle speeds of every "
     "lobe."),
    ("Surface finish",
     "The geometric marks left by the feed and the nose radius, then separate correction "
     "factors for tool runout, minimum chip thickness and general process effects."),
    ("What to change",
     "Suggested speeds come from the stability pockets that were actually solved for, "
     "and suggested feeds from inverting the roughness equation. Nothing here is a "
     "fixed list of advice."),
]


def render_how_it_works() -> None:
    st.markdown("#### From your numbers to the verdict")
    st.markdown('<div class="rule"></div>', unsafe_allow_html=True)
    for col, (i, (title, body)) in zip(st.columns(4, gap="medium"), enumerate(STEPS, 1)):
        with col:
            st.markdown(f'<div class="step-num">{i}</div>', unsafe_allow_html=True)
            st.markdown(f"**{title}**")
            st.caption(body)

    st.markdown("#### Symbols")
    with st.expander("What each variable means", expanded=False):
        st.markdown("""
**You type these in**

| Symbol | Name | Unit | What it is |
|---|---|---|---|
| D | Cutter diameter | mm | Diameter of the tool |
| N or z | Number of teeth | – | Flutes or inserts doing the cutting |
| n | Spindle speed | rpm | Revolutions per minute |
| a<sub>p</sub> | Axial depth of cut | mm | Depth along the tool axis — the one chatter cares about |
| a<sub>e</sub> | Radial width of cut | mm | Sideways engagement; a<sub>e</sub>/D is the immersion |
| f<sub>z</sub> | Feed per tooth | mm/tooth | Chip advance per tooth; sets the finish |
| r<sub>ε</sub> | Nose radius | mm | Corner radius of the insert |
| r<sub>e</sub> | Edge radius | µm | Sharpness of the cutting edge; matters in micro-milling |
| K<sub>t</sub> | Tangential cutting force coefficient | N/mm² | Force per unit chip area; a material property in practice |
| K<sub>r</sub> | Radial force ratio | – | K<sub>n</sub>/K<sub>t</sub>, how much force pushes sideways |
| f<sub>n</sub> | Natural frequency | Hz | From a tap test, per direction |
| ζ | Damping ratio | – | From the same tap test; 0.03 means 3% |
| k | Modal stiffness | N/m | Force needed per metre of deflection |
| TIR | Tool runout | µm | Radial throw of one tooth relative to the others |

**The app works these out**

| Symbol | Name | Unit | What it is |
|---|---|---|---|
| a<sub>lim</sub> | Limiting axial depth | mm | Deepest stable cut at that spindle speed |
| margin | a<sub>lim</sub>/a<sub>p</sub> | – | Above 1 is stable; 1.3 or more is a working margin |
| f<sub>c</sub> | Chatter frequency | Hz | Frequency the vibration would grow at, near f<sub>n</sub> |
| f<sub>TP</sub> | Tooth passing frequency | Hz | n·N/60; the forcing frequency of the cut |
| v<sub>c</sub> | Cutting speed | m/min | π·D·n/1000 |
| f | Feed rate | mm/min | n·N·f<sub>z</sub> |
| MRR | Material removal rate | mm³/min | a<sub>p</sub>·a<sub>e</sub>·f |
| R<sub>a</sub> | Arithmetic mean roughness | µm | Average height deviation of the surface |
| R<sub>z</sub> | Peak-to-valley height | µm | Roughly 4·R<sub>a</sub> for feed marks |
| k | Lobe number | – | 0, 1, 2… one waviness cycle more per tooth period |

**Inside the equations**

| Symbol | Name | What it is |
|---|---|---|
| Φ(iω) | Receptance, FRF | Deflection per unit force at frequency ω, from f<sub>n</sub>, ζ and k |
| α | Directional coefficients | Directional factors averaged over one tooth period |
| φ<sub>st</sub>, φ<sub>ex</sub> | Entry and exit angles | Where the tooth enters and leaves the cut, set by a<sub>e</sub>/D |
| Λ | Eigenvalue | Complex root of the characteristic equation; Λ<sub>R</sub> gives a<sub>lim</sub> |
| κ | Λ<sub>I</sub>/Λ<sub>R</sub> | Ratio that fixes the phase, and so the lobe speeds |
| ε | Phase shift | Between successive wavy surfaces; ε = π − 2·arctan κ |
| T | Tooth period | Time between one tooth and the next, 60/(n·N) |
""", unsafe_allow_html=True)

    st.markdown("#### The equations")
    st.markdown(
        "Stability, after Altintas and Budak (1995). With the averaged directional "
        "coefficients α and the receptances Φ:")
    st.latex(r"a_0\Lambda^2 + a_1\Lambda + 1 = 0")
    st.latex(r"a_{lim} = -\frac{2\pi\Lambda_R}{N\,K_t}\left(1+\kappa^2\right),"
             r"\qquad \kappa = \frac{\Lambda_I}{\Lambda_R}")
    st.latex(r"\varepsilon = \pi - 2\tan^{-1}\kappa, \qquad "
             r"T = \frac{\varepsilon + 2k\pi}{\omega_c}, \qquad n = \frac{60}{N\,T}")
    st.markdown("Surface finish, from the geometry of the marks left behind:")
    st.latex(r"R_z = \frac{f^2}{8r_\varepsilon}, \qquad R_a = \frac{f^2}{32 r_\varepsilon}"
             r"\qquad\text{(nose radius)}")
    st.latex(r"R_z \approx \frac{f_z^2}{8R} \quad\text{(end-milled wall)}, \qquad "
             r"h = R - \sqrt{R^2 - (a_e/2)^2} \quad\text{(ball-nose scallop)}")

    st.markdown("#### What the model assumes")
    st.markdown(
        "- A regular-pitch cutter, constant spindle speed and linear cutting force "
        "coefficients\n"
        "- A rigid workpiece whose dynamics do not change as material comes off\n"
        "- Directional factors averaged over the tooth period, which is accurate at "
        "moderate to high radial immersion\n"
        "- Roughness set by the feed marks, with wear, built-up edge and side flow "
        "lumped into one process factor")

    st.markdown("#### Where it stops")
    st.markdown(
        "- **Very low radial immersion and variable-pitch cutters.** Extra lobes appear "
        "that the averaged model cannot see. Semi-discretisation or a time-domain "
        "simulation is the right tool there.\n"
        "- **Low spindle speeds.** Process damping, where the flank rubs against the "
        "wavy surface, makes real cuts more stable than this predicts. That band is "
        "greyed out in the diagrams.\n"
        "- **The inputs, not the equations.** Modal parameters and cutting force "
        "coefficients dominate the answer. The presets are representative of classes "
        "of tool and material, not measurements of your machine.")
    st.caption("A teaching and planning aid, not a certified process guarantee. Confirm "
               "on the machine with a light test cut before committing a part.")


# -------------------------------------------------------------------------
# views/sources.py
# -------------------------------------------------------------------------
# Where the models, the constants and the validation data come from.



def render_sources() -> None:
    st.markdown("#### About the model")
    st.markdown("""
- **No machine-learning model is used.** RajMill solves the chatter stability equations
  directly, so there is nothing trained, nothing fitted to a dataset, and no accuracy
  figure to quote. The same inputs always give the same answer, and every number in the
  verdict can be traced back to an equation.
- **Stability:** zero-order analytical solution in the frequency domain. The directional
  coefficients are averaged over one tooth period, and the resulting quadratic
  eigenvalue problem is solved at each chatter frequency to give the limiting axial
  depth and the lobe speeds.
- **Surface finish:** geometric roughness from the marks the tool leaves, then explicit
  factors for tool runout, minimum chip thickness (the ploughing regime in micro-milling)
  and a general process factor. Each factor is shown separately in the Roughness tab
  rather than folded into one number.
- **Recommendations:** computed, not canned. Suggested speeds are the peaks of stability
  pockets that the solver found, with their width in rpm; suggested feeds come from
  inverting the roughness equation for your target Ra.
- **Checks performed:** lobe speeds land at 60·fn/(N·k) as they should; the predicted
  chatter frequency sits just above the natural frequency; the critical depth rises as
  radial immersion falls (1.72 mm slotting, 4.54 mm at half immersion, 28.7 mm at 10%
  for the same system).
""")

    st.markdown("#### Method references")
    st.markdown("""
1. **Altintas, Y. and Budak, E.** (1995). Analytical prediction of stability lobes in
   milling. *CIRP Annals* 44(1), 357-362. The stability solution used here.
2. **Altintas, Y.** (2012). *Manufacturing Automation: Metal Cutting Mechanics, Machine
   Tool Vibrations, and CNC Design*, 2nd ed., Cambridge University Press. Cutting force
   coefficients, tap testing and the roughness geometry.
3. **Budak, E. and Altintas, Y.** (1998). Analytical prediction of chatter stability in
   milling, Parts I and II. *Journal of Dynamic Systems, Measurement, and Control* 120(1),
   22-36.
4. **Insperger, T. and Stepan, G.** (2011). *Semi-Discretization for Time-Delay Systems*,
   Springer. The method to reach for at low radial immersion and with variable-pitch
   cutters, which this app does not cover.
5. **Schmitz, T. L. and Smith, K. S.** (2019). *Machining Dynamics: Frequency Response to
   Improved Productivity*, 2nd ed., Springer. Tap testing, receptance coupling and
   process damping.
6. **ISO 1302** roughness grades N1 to N12, used to put a grade next to the predicted Ra.
""")

    st.markdown("#### Open datasets for checking the predictions")
    st.markdown("""
None of these are used to train anything - RajMill needs no training data. They are the
public recordings a student can use to test whether a prediction was right, and they are
where a chatter-detection project would start.

1. **i-CNC: vibration data with chatter indication during milling** (Zenodo, CC BY 4.0):
   [zenodo.org/records/15308467](https://zenodo.org/records/15308467)
   - X and Y accelerations at 10 kHz on two CNC machines, spindle speed logged alongside,
     each measurement tagged for chatter. About 3 GB, so take a subset.
2. **Turning dataset for chatter diagnosis using machine learning** (Mendeley Data):
   [doi.org/10.17632/hvm4wh3jzx.1](https://doi.org/10.17632/hvm4wh3jzx.1)
   - Two single-axis accelerometers, a triaxial accelerometer, a microphone and a laser
     tachometer, tagged no-chatter, intermediate chatter, chatter and unknown, at four
     stickout lengths. Turning rather than milling, but it is the set most chatter papers
     benchmark against, and the tagging procedure is documented.
3. **PHM 2010 data challenge: high-speed CNC milling cutter wear**
   ([phmsociety.org](https://phmsociety.org/phm_competition/2010-phm-society-conference-data-challenge/)):
   dynamometer, accelerometer and acoustic emission at 50 kHz with wear measurements.
4. **NASA milling data set** (Agogino and Goebel, NASA Prognostics Data Repository):
   [nasa.gov/.../pcoe-data-set-repository](https://www.nasa.gov/intelligent-systems-division/discovery-and-systems-health/pcoe/pcoe-data-set-repository/)
   - Sixteen tools run to failure under eight conditions, with acoustic emission,
     vibration and current at 250 Hz. Useful for wear trends, too slow for chatter.
5. **Signal segmentation for milling process** (IEEE DataPort, open access):
   [ieee-dataport.org/open-access/signal-segmentation-milling-process](https://ieee-dataport.org/open-access/signal-segmentation-milling-process)
   - Three-axis spindle accelerometer in CSV at 2048 Hz, windowed and labelled dry run
     versus milling. Small files and a free login, so it is the easiest classroom start.
6. **MU-TCM face-milling dataset** (Mondragon Unibertsitatea, *Scientific Data* 2025):
   [doi.org/10.1038/s41597-025-05168-5](https://doi.org/10.1038/s41597-025-05168-5)
   - Cutting forces, vibration and acoustic emission with tool wear annotated before
     each experiment.
""")

    st.markdown("#### Constants used in the app")
    st.markdown("""
- **Cutting force coefficients (Kt, Kr)** in the material list are order-of-magnitude
  values for each material group. They change with tool geometry, coating, chip thickness
  and cutting speed, so calibrate them from your own force measurements before quoting a
  limiting depth to two decimal places.
- **Modal presets (fn, ζ, k)** are representative of the classes of tool named, not
  measurements of any particular machine. A tap test on your own spindle and tool takes
  ten minutes and replaces all of them.
""")

    st.markdown("#### Software")
    st.markdown("""
- [Streamlit](https://streamlit.io) for the web app, [Plotly](https://plotly.com/python/)
  for the charts
- [NumPy](https://numpy.org) and [SciPy](https://scipy.org) for the solver,
  [pandas](https://pandas.pydata.org) for the tables
- Machining guidance in the recommendations compiled from standard machining-dynamics
  practice for teaching use
""")
    st.caption("All referenced datasets and publications remain the property of their "
               "respective owners and are cited here only for teaching and "
               "non-commercial course purposes.")


# ---------------------------------------------------------------------------
# Module aliases: the real project splits this code across core/ and views/,
# and the code below refers to those modules by their short names. In one file
# they all point back here.
# ---------------------------------------------------------------------------
import sys as _sys

_self = _sys.modules[__name__]
theme = dy = rg = rc = inputs = _self


# ---------------------------------------------------------------------------
# Application
# ---------------------------------------------------------------------------
SETTINGS = {"site_name": "RajMill",
            "tagline": "Chatter stability and surface finish for milling",
            "lab_name": "Centre for Innovative Manufacturing Research",
            "timezone": "Asia/Kolkata",
            "counter": "badge",
            "badge_host": "rajmill.streamlit.app",
            "credit": "This app is built by Dr. Gururaja S, CIMR-VIT, for course purposes "
                      "only, using standard machining-dynamics models."}
try:
    SETTINGS.update(json.loads((ROOT / "settings.json").read_text()))
except Exception:
    pass

setup(SETTINGS["site_name"])
header(SETTINGS)

_s = sidebar()
_res = solve(dyn_key(_s.dyn), _s.teeth, _s.Kt, _s.Kr, _s.angles, speed_range(_s), _s.dyn)

_t1, _t2, _t3, _t4 = st.tabs(
    ["Predict my cut", "Process map", "How it works", "Sources"])
with _t1:
    render_predict(_s, _res)
with _t2:
    render_process_map(_s, _res)
with _t3:
    render_how_it_works()
with _t4:
    render_sources()

if str(SETTINGS.get("counter", "badge")).lower() == "badge":
    _badge = (f"https://hits.sh/{SETTINGS['badge_host']}.svg?label=Total%20visits"
              "&color=4169e1&labelColor=555555&style=flat-square")
    st.markdown(f"<div style='text-align:center;margin-top:28px'>"
                f"<img src='{_badge}' alt='visits'></div>", unsafe_allow_html=True)
