"""Flatten RajMill into one self-contained app.py.

Streamlit Community Cloud runs the repo as-is, so if the core/ and views/
folders do not reach GitHub (a common problem when files are uploaded one at a
time through the web interface), `from core import theme` fails. This script
pastes every module into a single file that imports nothing local, which
deploys even if only one file makes it into the repo.

    python tools/build_single_file.py        # writes single_file/app.py

Edit the real modules, then re-run this. Do not hand-edit the output.
"""
from __future__ import annotations

import ast
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "single_file" / "app.py"

# Order matters: module-level code runs as it is pasted.
MODULES = [
    ("core/theme.py", {}),
    ("core/dynamics.py", {}),
    ("core/roughness.py", {}),
    ("core/recommend.py", {}),
    ("core/inputs.py", {}),
    ("views/predict.py", {"render": "render_predict"}),
    ("views/process_map.py", {"render": "render_process_map"}),
    ("views/how_it_works.py", {"render": "render_how_it_works"}),
    ("views/sources.py", {"render": "render_sources"}),
]

# Every top-level import is dropped: the header below provides them all once.
# Anything a module needs must therefore appear in HEADER.
DROP = re.compile(r"^(from\s+\S+\s+import\b|import\s+\S+)")

HEADER = '''"""
RajMill - milling chatter stability and surface finish predictor (single file)

Generated by tools/build_single_file.py - do not edit this file directly.
Edit core/ and views/ in the main project, then re-run the build script.

Deploy: put this one file plus requirements.txt in a repo and point Streamlit
Community Cloud at app.py. Nothing else is needed.
"""
from __future__ import annotations

import json
import warnings
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.io as pio
import streamlit as st

ROOT = Path(__file__).resolve().parent
'''

FOOTER = '''

# ---------------------------------------------------------------------------
# Module aliases: the real project splits this code across core/ and views/,
# and the code below refers to those modules by their short names. In one file
# they all point back here.
# ---------------------------------------------------------------------------
import sys as _sys

_self = _sys.modules[__name__]
theme = dy = rg = rc = inputs = _self


# ---------------------------------------------------------------------------
# Application
# ---------------------------------------------------------------------------
SETTINGS = {"site_name": "RajMill",
            "tagline": "Chatter stability and surface finish for milling",
            "lab_name": "Centre for Innovative Manufacturing Research",
            "timezone": "Asia/Kolkata",
            "counter": "badge",
            "badge_host": "rajmill.streamlit.app",
            "credit": "This app is built by Dr. Gururaja S, CIMR-VIT, for course purposes "
                      "only, using standard machining-dynamics models."}
try:
    SETTINGS.update(json.loads((ROOT / "settings.json").read_text()))
except Exception:
    pass

setup(SETTINGS["site_name"])
header(SETTINGS)

_s = sidebar()
_res = solve(dyn_key(_s.dyn), _s.teeth, _s.Kt, _s.Kr, _s.angles, speed_range(_s), _s.dyn)

_t1, _t2, _t3, _t4 = st.tabs(
    ["Predict my cut", "Process map", "How it works", "Sources"])
with _t1:
    render_predict(_s, _res)
with _t2:
    render_process_map(_s, _res)
with _t3:
    render_how_it_works()
with _t4:
    render_sources()

if str(SETTINGS.get("counter", "badge")).lower() == "badge":
    _badge = (f"https://hits.sh/{SETTINGS['badge_host']}.svg?label=Total%20visits"
              "&color=4169e1&labelColor=555555&style=flat-square")
    st.markdown(f"<div style='text-align:center;margin-top:28px'>"
                f"<img src='{_badge}' alt='visits'></div>", unsafe_allow_html=True)
'''


def docstring_to_comment(text: str) -> str:
    """Turn a module's leading docstring into # comments.

    Streamlit "magic" prints any bare string literal in the main script, so a
    module docstring pasted into the middle of app.py would show up on the page.
    """
    tree = ast.parse(text)
    if not (tree.body and isinstance(tree.body[0], ast.Expr)
            and isinstance(getattr(tree.body[0], "value", None), ast.Constant)
            and isinstance(tree.body[0].value.value, str)):
        return text
    node = tree.body[0]
    lines = text.split("\n")
    doc = ast.get_docstring(tree, clean=True) or ""
    comment = "\n".join(("# " + ln).rstrip() for ln in doc.split("\n"))
    return "\n".join(lines[:node.lineno - 1] + [comment] + lines[node.end_lineno:])


def inline(path: str, renames: dict[str, str]) -> str:
    text = docstring_to_comment((ROOT / path).read_text())
    kept = [ln for ln in text.split("\n") if not DROP.match(ln)]
    body = "\n".join(kept).strip("\n")
    for old, new in renames.items():
        body = re.sub(rf"^def {old}\(", f"def {new}(", body, flags=re.M)
    rule = "# " + "-" * 73
    return f"\n\n{rule}\n# {path}\n{rule}\n{body}\n"


def main() -> None:
    parts = [HEADER]
    for path, renames in MODULES:
        parts.append(inline(path, renames))
    parts.append(FOOTER)
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("".join(parts))
    (OUT.parent / "requirements.txt").write_text((ROOT / "requirements.txt").read_text())
    lines = OUT.read_text().count("\n")
    print(f"Wrote {OUT.relative_to(ROOT)} ({lines} lines) and requirements.txt")
    print("Deploy those two files alone, with app.py as the main file.")


if __name__ == "__main__":
    main()
